name: SecureChests-Simple
main: me.odium.securechestssimple.SecureChests
version: 0.5.1
author: HAklowner
website: http://dev.bukkit.org/server-mods/secure-chests
description: SecureChests - Simple chest locking!
commands:
   lock:
      description: lock your chests
   unlock:
      description: unlock your chests
   sc:
      description: lock your chests securely
   securechests:
      description: lock your chests securely
   securechest:
      description: lock your chests securely