name: SecureChests-Simple
main: me.odium.securechestssimple.SecureChests
version: 0.3.1
author: HAklowner - Original Version Maintained by Odium
description: SecureChests-Simple - A less bloated alternative to SecureChests
commands:
   lock:
      description: lock your chests
   unlock:
      description: unlock your chests
   sc:
      aliases: [securechest, securechests]
      description: lock your chests securely